config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'map', to: 'pages#map'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  patch 'users/:id/edit', to: 'users#update'
  get 'login', to: 'sessions#new'
  get 'easylogin', to: 'sessions#easy'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'password_resets/new'
  get 'password_resets/edit'
  patch 'password_resets/:id/edit', to: 'password_resets#update'
  get 'password_resets', to: 'password_resets#new'
  get 'search', to: 'searches#search'
  get 'sort', to: 'searches#sort'
  resources :users, only: %i[show new create edit update destroy] do
    member do
      patch 'update_avatar'
      get 'following'
      get 'followers'
      get 'related_info'
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :microposts, only: %i[index new create destroy]
  resources :relationships, only: %i[create destroy]
  resources :goings, only: %i[create destroy]
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :getting_user,            only: %i[edit update]
  before_action :valid_user,              only: %i[edit update]
  before_action :check_expiration,        only: %i[edit update]
  before_action :already_authenticated?,  only: %i[edit update]

  def new; end

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:success] = 'パスワード再発行用のメールを送信しました'
      redirect_to root_url
    else
      flash.now[:danger] = 'メールアドレスは見つかりませんでした'
      render 'new'
    end
  end

  def edit; end

  def update
    if params[:user][:password].empty?
      @user.errors.add(:password, :blank)
      render 'edit'
    elsif @user.update(user_params)
      log_in @user
      @user.update_attribute(:reset_digest, nil)
      flash[:success] = 'パスワードを変更しました'
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  # ユーザーがデータベースに存在するか確認する
  def getting_user
    @user = User.find_by(email: params[:email])
  end

  # 有効なユーザーかどうか確認する
  def valid_user
    unless @user && @user.activated? &&
           @user.authenticated?(:reset, params[:id])
      redirect_to root_url
    end
  end

  # トークンが期限切れかどうか確認する
  def check_expiration
    return unless @user.password_reset_expired?

    flash[:danger] = 'このリンクは期限切れです'
    redirect_to new_password_reset_url
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide(:title, 'パスワード再発行') %>

<h1 class="page-title">パスワード再発行</h1>
<div class="w-4/5 mx-auto my-10">
  <div class="max-w-sm mx-auto">

    <%= form_with(model: @user, url: edit_password_reset_path(params[:id], email: @user.email), local: true, class: "flex flex-col") do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= hidden_field_tag :email, @user.email %>

      <div class="mb-5">
        <%= f.label :password, "新しいパスワード", class: "label" %>
        <%= f.password_field :password, class: 'field' %>
      </div>

      <div class="mb-12">
        <%= f.label :password_confirmation, "新しいパスワード（確認）", class: "label" %>
        <%= f.password_field :password_confirmation, class: 'field' %>
      </div>

      <%= f.submit "パスワードを変更", class: "btn-green py-2 px-6 mx-auto" %>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<% provide(:title, "パスワードを忘れた") %>

<h1 class="page-title">パスワードを忘れた</h1>
<div class="w-4/5 mx-auto my-10">
  <div class="max-w-sm mx-auto">

    <%= form_with(url: password_resets_path, scope: :password_reset, local: true, class: "flex flex-col") do |f| %>

      <div class="mb-12">
        <%= f.label :email, "メールアドレス", class: "label" %>
        <%= f.email_field :email, class: 'field' %>
      </div>

      <%= f.submit "送信", class: "btn-green w-32 py-2 mx-auto" %>
    <% end %>
  </div>
</div>