config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'map', to: 'pages#map'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  patch 'users/:id/edit', to: 'users#update'
  get 'login', to: 'sessions#new'
  get 'easylogin', to: 'sessions#easy'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'password_resets/new'
  get 'password_resets/edit'
  patch 'password_resets/:id/edit', to: 'password_resets#update'
  get 'password_resets', to: 'password_resets#new'
  get 'search', to: 'searches#search'
  get 'sort', to: 'searches#sort'
  resources :users, only: %i[show new create edit update destroy] do
    member do
      patch 'update_avatar'
      get 'following'
      get 'followers'
      get 'related_info'
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :microposts, only: %i[index new create destroy]
  resources :relationships, only: %i[create destroy]
  resources :goings, only: %i[create destroy]
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token

  has_one_attached :avatar
  has_many :microposts, dependent: :destroy
  has_many :active_relationships, class_name: 'Relationship',
                                  foreign_key: 'follower_id',
                                  dependent: :destroy
  has_many :passive_relationships, class_name: 'Relationship',
                                   foreign_key: 'followed_id',
                                   dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :goings, dependent: :destroy
  has_many :gone_microposts, through: :goings, source: :micropost

  validates :name,  presence: true, length: { maximum: 20 }, uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validates :avatar, content_type: { in: %w[image/jpeg image/gif image/png],
                                     message: 'のフォーマットが正しくありません' },
                     size: { less_than: 2.megabytes,
                             message: 'のサイズは2MB以下にしてください' }

  before_save   :downcase_email
  before_create :create_activation_digest

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?

    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids})", user_id: id)
    # Micropost.where("user_id IN (#{following_ids})
    #                  OR user_id = :user_id", user_id: id)
  end

  # アカウントを有効にする
  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  # 有効化用のメールを送信する
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # パスワード再発行の属性を設定する
  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)
  end

  # パスワード再発行のメールを送信する
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # パスワード再発行の期限が切れている場合はtrueを返す
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  # ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  # 既に「行ってみたい」ボタンを押していればtrue
  def already_gone?(micropost)
    goings.where(micropost_id: micropost.id).exists?
  end

  private

  # メールアドレスをすべて小文字にする
  def downcase_email
    self.email = email.downcase
  end

  # 有効化トークンとダイジェストを作成および代入する
  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user,          only: %i[edit update destroy]
  before_action :correct_user,            only: %i[edit update]
  before_action :already_authenticated?,  only: %i[new create]
  protect_from_forgery except: :destroy

  def show
    @user = User.find(params[:id])
  end

  def related_info
    @sort = 'nil'
    @pagination = params[:pagination]
    @info = params[:info]
    @user = User.find(params[:id])
    @feed_items = @user.feed.page(params[:page])
    case params[:info]
    when 'posted'
      @microposts = Micropost.where(user_id: @user.id).page(params[:page])
    when 'checked'
      @microposts = @user.gone_microposts.page(params[:page])
    when 'favorite'
      @users = @user.following
      # byebug
    end
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:success] = '確認メールを送信しました'
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:success] = '更新しました'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def update_avatar
    # byebug
    @user = User.find(params[:id])
    @user.avatar.attach(params[:user][:avatar])
    respond_to do |format|
      format.html { redirect_to edit_user_path(@user) }
      format.js
    end
  end

  def destroy
    @user = User.find(params[:id])
    if current_user.admin?
      if current_user == @user
        flash[:danger] = '管理ユーザーは削除できません'
      else
        @user.destroy
        flash[:danger] = 'アカウントを削除しました'
      end
    elsif current_user?(@user)
      @user.destroy
      flash[:danger] = 'アカウントを削除しました'
    end
    redirect_to root_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :avatar)
  end

  # beforeアクション
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def avatar_for(user, options = { size: 40 })
    size = options[:size]
    if user.avatar.attached?
      image_tag(user.avatar.variant(gravity: :center,
                                    resize: "#{size}x#{size}^",
                                    crop: "#{size}x#{size}+0+0"),
                id: "user#{user.id}-avatar", alt: 'user-avatar',
                class: 'hover:opacity-50 rounded-full border border-indigo-200 shadow-md')
    else
      image_tag('default_icon.jpg', width: "#{size}px",
                                    id: "user#{user.id}-avatar", alt: 'user-avatar',
                                    class: 'rounded-full hover:opacity-50')
    end
  end
end

app/views/users/_edit_form.html.erb
<%= form_with(model: @user, local: true, url: edit_user_path(current_user), class: "flex flex-col" ) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="mb-5">
    <%= f.label :name, "ユーザー名（他のユーザーに公開されます）", class: "label" %>
    <%= f.text_field :name, class: "field" %>
  </div>

  <div class="mb-5">
    <%= f.label :email, "メールアドレス（非公開）", class: "label" %>
    <%= f.email_field :email, class: "field" %>
  </div>

  <div class="mb-5">
    <%= f.label :password, "パスワード", class: "label" %>
    <%= f.password_field :password, class: "field" %>
  </div>

  <div class="mb-12">
    <%= f.label :password_confirmation, "パスワード（確認）", class: "label" %>
    <%= f.password_field :password_confirmation, class: "field" %>
  </div>

  <%= f.submit yield(:button_text), class: "btn-green w-32 h-10 mx-auto" %>
<% end %>

app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "ユーザーをお気に入りに登録", class: "btn-blue py-2 px-6 text-xl" %>
<% end %>

app/views/users/_follow_form.html.erb
<div id="follow_form" class="py-10 text-center">

<% if !logged_in? %>
  <%= form_with(model: Relationship, remote: true) do |f| %>
    <div><%= hidden_field_tag :followed_id, @user.id %></div>
    <%= f.submit "ユーザーをお気に入りに登録", class: "btn-blue py-2 px-6 text-xl" %>
  <% end %>

<% elsif current_user.following?(@user) %>
  <%= render 'unfollow' %>

<% else %>
  <%= render 'follow' %>
<% end %>

</div>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true, url: signup_path, class: "flex flex-col" ) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>


  <div class="mb-5">
    <%= f.label :name, "ユーザー名（他のユーザーに公開されます）", class: "label" %>
    <%= f.text_field :name, class: "field" %>
  </div>

  <div class="mb-5">
    <%= f.label :email, "メールアドレス（非公開）", class: "label" %>
    <%= f.email_field :email, class: "field" %>
  </div>

  <div class="mb-5">
    <%= f.label :password, "パスワード", class: "label" %>
    <%= f.password_field :password, class: "field" %>
  </div>

  <div class="mb-12">
    <%= f.label :password_confirmation, "パスワード（確認）", class: "label" %>
    <%= f.password_field :password_confirmation, class: "field" %>
  </div>

  <%= f.submit yield(:button_text), class: "btn-green w-32 h-10 mx-auto" %>
<% end %>

app/views/users/_related_info.html.erb
<% if @users %>
  <div class="w-11/12 mx-auto pt-10 border-b-2">
    <ul class="flex flex-wrap justify-items-start space-x-2 md:space-x-5 w-11/12 mx-auto mb-6">
      <%= render @users %>
    </ul>
    <% if @feed_items.present? %>
      <div class="text-center mb-6">
        <%= link_to "地図で見る", map_path(microposts_ids: @feed_items.ids), class: "btn-blue inline-block py-2 px-8 mx-auto font-semibold text-lg text-center" %>
      </div>
    <% end %>
    <div class="">
      <%= render 'shared/microposts', microposts: @feed_items %>
    </div>
  </div>

<% else %>
  <div class="w-11/12 mx-auto pt-10 border-b-2">
    <% if @microposts.present? %>
      <div class="text-center mb-6">
      <%= link_to "地図で見る", map_path(microposts_ids: @microposts.ids), class: "btn-blue inline-block py-2 px-8 mx-auto font-semibold text-lg text-center" %>
      </div>
    <% end %>
    <%= render 'shared/microposts', microposts: @microposts %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id), html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "お気に入り解除", data: { confirm: "お気に入り登録を解除します。"}, class: "btn-disabled py-2 px-6 text-xl" %>
<% end %>

app/views/users/_user.html.erb
<li class="inline-block w-24 md:w-32 py-3 md:py-6 px-1 md:px-2 mb-4 ml-2 md:ml-5 border border-gray-800 rounded text-center">
  <div class="">
    <%= link_to avatar_for(user, size: 70), user, class: 'inline-block mb-2' %>
  </div>
  <div class="">
    <%= link_to user.name, user, class: 'inline-block h-6 w-20 md:w-24 align-middle truncate' %>
  </div>
  <% if logged_in? && current_user.admin? && !current_user?(user) %>
    <%= link_to "delete", user, method: :delete, data: { confirm: "削除を実行します" }, class: 'btn-red px-2' %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'アカウント編集') %>
<% provide(:button_text, '更新') %>

<h1 class="page-title ">アカウント編集</h1>
<div class="w-4/5 mx-auto my-10">

  <!-- ユーザーアバター表示と変更リンク -->
  <div class="mb-5">
    <%= form_with model: @user, url: update_avatar_user_path(@user), id: :avatar_form, class: "text-center" do |f| %>
      <%= f.label :avatar, content_tag(:div, avatar_for(@user, size: 100), id: "update_avatar_wrapper"), class: "inline-block ursor-pointer" %>
      <%= f.file_field :avatar, accept: "image/jpeg,image/gif,image/png", class: "hidden" %>
    <% end %>
  </div>

  <div class="max-w-sm mx-auto">
    <%= render 'edit_form' %>
  </div>

  <div class="max-w-sm mx-auto text-center">
    <% unless @user.admin? %>
      <%= link_to "アカウント削除", @user, method: :delete, data: { confirm: 'このアカウントを削除します。この操作は取り消せません。よろしいですか？' }, class: "btn-red inline-block py-2 px-4 mt-20" %>
    <% end %>
  </div>
</div>

<!-- 画像サイズチェック -->
<%= javascript_pack_tag 'avatar_size_check/application' %>

app/views/users/new.html.erb
<% provide(:title, 'アカウント作成') %>
<% provide(:button_text, '登録') %>

<h1 class="page-title">アカウント作成</h1>
<div class="w-4/5 mx-auto my-10">
  <div class="max-w-sm mx-auto">
    <div>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/related_info.js.erb
// 関連情報を更新
document.getElementById('related-info').innerHTML = `<%= render 'related_info' %>`;

// ページネーションクリック時のスクロール設定
function paginationScroll() {
  const pagination = document.getElementById('microposts-wrapper').dataset.pagination;
  if (pagination === "true") {
    document.getElementById('related-info').scrollIntoView({  
      behavior: 'smooth'  
    });
  }
}
paginationScroll();

// モーダル時の背景のスクロール固定設定
function setModal() {
  const triggers = document.getElementsByClassName('grad-trigger');
  const body = document.getElementsByTagName('body');
  for (let i = 0; i < triggers.length; i++){
    triggers[i].addEventListener('click', () => {
      if (triggers[i].checked) {
        const posi = window.pageYOffset;
        body[0].style.position = 'fixed';
        body[0].style.top = `${-1 * posi}` + "px";
        triggers[i].dataset.num = posi;
    
        // iframe読み込みをクリック時のみに設定
        const iframe = triggers[i].nextElementSibling.nextElementSibling.getElementsByTagName('iframe');
        if (iframe[0].src === "about:blank") {
          iframe[0].setAttribute("src", iframe[0].dataset.src);
        }

      } else {
        body[0].style.position = 'static';
        const position = triggers[i].dataset.num;
        scrollTo(0, position);
      }
    });
  }
}
setModal();

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="w-11/12 mx-auto border-b-2">

  <div class="mt-16 mb-16 text-center">
    <!-- ログインユーザーなら編集ページへのリンク表示 -->
    <div class="inline-block text-center">
      <% if current_user?(@user) %>
        <%= link_to avatar_for(@user, size: 150), edit_user_path(@user) %>
      <% else %>
        <%= link_to avatar_for(@user, size: 150), @user %>
      <% end %>
    </div>
    <p class="mt-2 text-xl"><%= @user.name %></p>
  </div>

  <div class="flex justify-around max-w-md mx-auto mb-20">
    <div class="w-32 text-center">
      <%= link_to @user.microposts.count, related_info_user_path(@user, info: "posted"), {remote: true, class: "number"} %>
      <p class="bg-tw-gray text-gray-600 text-sm">投稿数</p>
    </div>
    <div class="w-32 text-center">
      <%= link_to @user.goings.count, related_info_user_path(@user, info: "checked"), {remote: true, class: "number"} %>
      <p class="bg-tw-gray text-gray-600 text-sm">
        <%= image_tag("pin_red.svg", alt: "pin", width: "18px", class: "margin-bottom-2px inline-block") %>チェック記事
      </p>
    </div>
    <div class="w-32 text-center">
      <%= link_to @user.following.count, related_info_user_path(@user, info: "favorite"), {remote: true, class: "number"} %>
      <p class="bg-tw-gray text-gray-600 text-sm truncate">お気に入りユーザー</p>
    </div>
  </div>


  <div class="flex flex-col mr-6 text-right">
    <p class="text-gray-600 text-sm">
      アカウント作成日：<%= l @user.created_at, format: :y_m_d %>
    </p>
  </div>

</div>


<!-- Ajax用 -->
<div id="related-info">
</div>


<!-- ログインユーザーなら編集とログアウトリンク、他ユーザーならお気に入り登録ボタン -->
<div class="w-11/12 mx-auto">
  <% if current_user?(@user) %>
    <div class="max-w-xl mx-auto">
      <ul class="flex flex-col items-center sm:flex-row sm:justify-around py-10">
        <li><%= link_to "アカウント編集", edit_user_path(current_user), {class: "btn-green inline-block py-2 px-6 mb-4 sm:mb-0 text-xl"} %></li>
        <li><%= link_to "ログアウト", logout_path, method: :delete, class: "btn-red inline-block py-2 px-6 text-xl" %></li>
      </ul>
    </div>
  <% else %>
    <%= render 'follow_form' %>
  <% end %>
</div>

app/views/users/update_avatar.js.erb
document.getElementById("update_avatar_wrapper").innerHTML = `<%= avatar_for(@user, size: 80) %>`