config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'map', to: 'pages#map'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  patch 'users/:id/edit', to: 'users#update'
  get 'login', to: 'sessions#new'
  get 'easylogin', to: 'sessions#easy'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'password_resets/new'
  get 'password_resets/edit'
  patch 'password_resets/:id/edit', to: 'password_resets#update'
  get 'password_resets', to: 'password_resets#new'
  get 'search', to: 'searches#search'
  get 'sort', to: 'searches#sort'
  resources :users, only: %i[show new create edit update destroy] do
    member do
      patch 'update_avatar'
      get 'following'
      get 'followers'
      get 'related_info'
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :microposts, only: %i[index new create destroy]
  resources :relationships, only: %i[create destroy]
  resources :goings, only: %i[create destroy]
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  belongs_to :period, optional: true
  belongs_to :prefecture, optional: true
  has_many :goings, dependent: :destroy
  has_many :gone_users, through: :goings, source: :user

  validates :user_id, presence: true
  validates :latlng, presence: { message: 'を立ててください' }
  validates :prefecture_id, presence: { message: 'を選択してください' }
  validates :period_id, presence: { message: 'を選択してください' }
  validates :title, presence: true, length: { maximum: 40 }
  validates :content, presence: true, length: { maximum: 1000 }
  validates :image,
            content_type: { in: %w[image/jpeg image/gif image/png],
                            message: 'のフォーマットが正しくありません' },
            size: { less_than: 5.megabytes,
                    message: ' のサイズは5MB以下にしてください' }

  default_scope -> { order(created_at: :desc) }
  scope :search_keyword, lambda { |keyword|
    search_user(keyword).or(search_title(keyword)).or(search_content(keyword))
  }
  scope :search_user, lambda { |keyword|
    includes(:user).where(users: { name: keyword.to_s })
  }
  scope :search_title, lambda { |keyword|
    where('title LIKE ?', "%#{keyword}%")
  }
  scope :search_content, lambda { |keyword|
    where('content LIKE ?', "%#{keyword}%")
  }
  scope :search_prefecture, lambda { |prefecture_id|
    where(prefecture_id: prefecture_id) if prefecture_id.present?
  }
  scope :search_period, lambda { |period_id|
    where(period_id: period_id) if period_id.present?
  }

  def self.trend_by(period)
    case period
    when 'period-all'
      period_for = { created_at:
                     Time.zone.parse('20200101000000')...Time.zone.now }
    when 'period-month'
      period_for = { created_at: 1.month.ago...Time.zone.now }
    when 'period-week'
      period_for = { created_at: 1.week.ago...Time.zone.now }
    end
    Micropost.where(period_for)
             .joins(:goings)
             .group('micropost_id')
             .reorder('count(micropost_id) desc')
  end

  def self.search(search_words, prefecture_id, period_id)
    microposts = Micropost.all
    return microposts if search_words.blank? \
                      && prefecture_id.blank? \
                      && period_id.blank?

    keywords = search_words.split(/[[:blank:]]+/)
    keywords.delete('')

    results = keywords.inject(microposts) do |relation, keyword|
      relation.search_keyword(keyword)
    end
    results.search_prefecture(prefecture_id).search_period(period_id)
  end

  def self.sort_by(sort, microposts_ids)
    case sort
    when 'latest'
      sort_by = { created_at: 'desc' }
    when 'period-asc'
      sort_by = { period_id: 'asc' }
    when 'period-desc'
      sort_by = { period_id: 'desc' }
    end
    microposts = Micropost.where(id: microposts_ids).reorder(sort_by)
    [microposts, microposts.ids]
  end

  def self.sort_by_going(microposts_ids)
    microposts = Micropost.where(id: microposts_ids)
                          .includes(:gone_users)
                          .sort do |a, b|
                            b.gone_users.size <=> a.gone_users.size
                          end
    [microposts, microposts.map(&:id)]
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: %i[new create destroy]
  before_action :correct_user, only: :destroy
  protect_from_forgery except: :destroy

  def index
    # ページネーションをクリックされたかどうかの情報をビューに渡す
    @pagination = params[:pagination] || 'nil'
    # 並び替え初期値を最新順に設定
    @sort = 'latest'
    # microposts初期設定
    microposts = Micropost.all
    @microposts = microposts.page(params[:page])
    @microposts_ids = microposts.ids
    # byebug
  end

  def new
    @micropost = current_user.microposts.build
  end

  def create
    @micropost = current_user.microposts.build(micropost_params)
    @micropost.image.attach(params[:micropost][:image])
    # byebug
    if @micropost.save
      flash[:success] = '投稿しました'
      redirect_to microposts_url
    else
      render 'new'
    end
  end

  def destroy
    @micropost.destroy
    flash[:danger] = '投稿を削除しました'
    redirect_back(fallback_location: root_url)
  end

  private

  def micropost_params
    params.require(:micropost)
          .permit(:title, :content, :image, :period_id, :prefecture_id, :latlng)
  end

  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    redirect_to root_url if @micropost.nil?
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
  # def image_for(micropost, options = { size: 100 })
  def image_for(micropost)
    # size = options[:size]
    if micropost.image.attached?
      image_tag(micropost.image, width: '100%')
      # image_tag(micropost.image.variant(gravity: :center,
      #                                   resize:"160x120^",
      #                                   crop:"160x120+0+0"),
      #           id: "micropost#{micropost.id}-image", alt: 'micropost-image',
      #           class: '')
    else
      image_tag('no_image.png', width: '100%')
      # image_tag('no_image.png', :size => '160x120')
    end
  end
end

app/views/microposts/_going.html.erb
<!-- 非ログインユーザービュー -->
<% if !logged_in? %>

  <%= form_with(model: Going, class: "inline-block") do |f| %>
    <span><%= hidden_field_tag :micropost_id, micropost.id, {id: "hidden_micropost#{micropost.id}"} %></span>
    <%= button_tag type: :submit, class: "btn-blue inline-block pl-2 pr-3 text-sm align-middle going" do %>
      <%= image_tag("pin.svg", alt: "pin", width: "16px", class: "margin-bottom-2px inline-block align-middle leading-4") %>
      行ってみたい!
    <% end %>
    <span class="text-purple-500 align-middle leading-4 going-count"><%= micropost.goings.count %></span>
  <% end %>

<!-- ログインユーザービュー -->
<% elsif current_user.already_gone?(micropost) %>

  <%= form_with(model: current_user.goings.find_by(micropost_id: micropost.id), html: { method: :delete, class: "inline" }) do |f| %>
    <span><%= hidden_field_tag :micropost_id, micropost.id, {id: "hidden_micropost#{micropost.id}"} %></span>
    <%= button_tag type: :submit, class: "btn-disabled px-2 text-sm going" do %>
      チェックを外す
    <% end %>
    <span class="going-count"><%= micropost.goings.count %></span>
  <% end %>

<% else %>

  <%= form_with(model: current_user.goings.build, class: "inline-block") do |f| %>
    <span><%= hidden_field_tag :micropost_id, micropost.id, {id: "hidden_micropost#{micropost.id}"} %></span>
    <%= button_tag type: :submit, class: "btn-blue inline-block pr-3 pl-2 text-sm align-middle going" do %>
      <%= image_tag("pin.svg", alt: "pin", width: "16px", class: "margin-bottom-2px inline-block align-middle leading-4") %>
      行ってみたい!
    <% end %>
    <span class="text-purple-500 align-middle leading-4 going-count"><%= micropost.goings.count %></span>
  <% end %>

<% end %>

app/views/microposts/_microposts.html.erb
<% if microposts.present? %>
  <ol id="microposts" class="microposts">
    <%= render partial: 'microposts/micropost', collection: microposts %>
  </ol>
  <% if microposts.page(2).present? %>
    <%= paginate microposts, remote: true %>
  <% end %>
<% else %>
  <a href="/">home</a>
  <p>検索結果なし。</p>
<% end %>

app/views/microposts/_search_results.html.erb
<% unless params[:search].blank? && params[:prefecture_id].blank? && params[:period_id].blank? %>

  <div class="flex flex-col items-center">
    <span style="margin-top: 4px;" class="inline-block">
      <% if params[:search].present? %>
        <span class="text-lg">"<%= params[:search] %>"</span>
      <% end %>

      <% if params[:prefecture_id].present? %>
        <span class="text-lg">"<%= Prefecture.find(params[:prefecture_id]).name %>"</span>
      <% end %>

      <% if params[:period_id].present? %>
        <span class="text-lg">"<%= Period.find(params[:period_id]).name %>"</span>
      <% end %>

      の検索結果
    </span>
    <div class="flex flex-col md:flex-row md:justify-around md:w-11/12">

      <%= link_to "検索結果を地図で見る", map_path(microposts_ids: @microposts_ids), class: "btn-blue inline-block w-48 mt-2 md:mt-4" %>

      <%= link_to "Clear", microposts_path, class: "inline-block mt-4 hover:underline" %>
    </div>
  </div>

<% end %>

app/views/microposts/index.html.erb
<% provide(:title, "検索") %>

<h1 class="page-title">検索</h1>

<div class="w-11/12 mx-auto border-b-2 text-center">

  <!-- 検索フォーム -->
  <%= form_with url: search_path, class: "inline-block md:w-4/5 max-w-xl mt-8 mb-8 pt-10 px-8 pb-5 border border-gray-400 rounded bg-gray-200", method: :get do |f| %>
    <div class="md:flex md:justify-between">
      <%= f.search_field :search, class: "block w-64 mx-auto md:mr-6 mb-8 border border-gray-700 rounded leading-8", placeholder: "キーワード検索" %>
      <div class="mb-4 md:w-64">
        <%= f.collection_select :prefecture_id, Prefecture.all, :id, :name, {include_blank: '都道府県'}, {class: "tag md:mt-1 mr-4 md:mr-2 py-1"} %>
        <%= f.collection_select :period_id, Period.all, :id, :name, {include_blank: '時代'}, {class: "tag py-1"} %>
      </div>
    </div>
    <div class="mb-5 text-center">
      <%= f.submit 'Search', class: "btn-blue py-1 px-4 text-base font-semibold" %>
    </div>

    <!-- 検索結果とマップリンク表示 -->
    <div class="text-center">
      <div id="search-results"></div>
    </div>

  <% end %>

</div>

<!-- 並び替え -->
<fieldset id="fieldset" class="my-4 text-center">
  <input id="latest" class="radio-inline__input" type="radio" name="accessible-radio" checked="checked"/>
  <label for="latest" id="latest-label" class="radio-inline__label">
    <%= link_to "最新", sort_path(microposts_ids: @microposts_ids, sort: "latest"), {remote: true, class: "block p-3"} %>
  </label>

  <input id="going" class="radio-inline__input" type="radio" name="accessible-radio"/>
  <label for="going" id="going-label" class="radio-inline__label">
    <%= link_to "行ってみたい!", sort_path(microposts_ids: @microposts_ids, sort: "going"), {remote: true, class: "block p-3"} %>
  </label>

  <input id="period-asc" class="radio-inline__input" type="radio" name="accessible-radio"/>
  <label for="period-asc" id="period-asc-label" class="radio-inline__label">
    <%= link_to "時代昇順", sort_path(microposts_ids: @microposts_ids, sort: "period-asc"), {remote: true, class: "block p-3"} %>
  </label>

  <input id="period-desc" class="radio-inline__input" type="radio" name="accessible-radio"/>
  <label for="period-desc" id="period-desc-label" class="radio-inline__label">
    <%= link_to "時代降順", sort_path(microposts_ids: @microposts_ids, sort: "period-desc"), {remote: true, class: "block p-3"} %>
  </label>
</fieldset>

<!-- micropost表示 -->
<div id="microposts">
  <%= render 'shared/microposts', microposts: @microposts %>
</div>

<!-- 最初の読み込み時のみ必要 -->
<%= javascript_pack_tag 'modal/application' %>
<script>
// 検索結果とマップリンクを表示
document.getElementById('search-results').innerHTML = `<%= render 'microposts/search_results' %>`;
</script>

app/views/microposts/index.js.erb
// microostを更新
document.getElementById('microposts').innerHTML = `<%= render 'shared/microposts', microposts: @microposts %>`;

// ページネーションクリック時のスクロール設定
function paginationScroll() {
  const pagination = document.getElementById('microposts-wrapper').dataset.pagination;
  if (pagination === "true") {
    document.getElementById('microposts').scrollIntoView({  
      behavior: 'smooth'  
    });
  }
}
paginationScroll();

// モーダル時の背景のスクロール固定設定
function setModal() {
  let triggers = document.getElementsByClassName('grad-trigger');
  let body = document.getElementsByTagName('body');
  for (let i = 0; i < triggers.length; i++){
    triggers[i].addEventListener('click', () => {
      if (triggers[i].checked) {
        let posi = window.pageYOffset;
        body[0].style.position = 'fixed';
        body[0].style.top = `${-1 * posi}` + "px";
        triggers[i].dataset.num = posi;
    
        // iframe読み込みをクリック時のみに設定
        let iframe = triggers[i].nextElementSibling.nextElementSibling.getElementsByTagName('iframe');
        if (iframe[0].src === "about:blank") {
          iframe[0].setAttribute("src", iframe[0].dataset.src);
        }

      } else {
        body[0].style.position = 'static';
        let position = triggers[i].dataset.num;
        scrollTo(0, position);
      }
    });
  }
}
setModal();

app/views/microposts/new.html.erb
<% provide(:title, "投稿作成") %>

<!-- マップ描画 -->
<div style="height: min(70vw, 504px)" class="max-w-4xl mt-10 mx-auto border border-gray-400">
  <div id="post_map" style="height: 100%; width: 100%"></div>
  <div class="text-sm text-right">※ピンをダブルクリックか右クリックで拡大</div>
</div>
<!-- マップに入れるHTML -->
<input id="autocomplete" size="23" class="mt-3 ml-3 h-6 rounded-sm shadow text-base" type="search" placeholder="検索（候補をクリック）" />
<div id="init-position" class="map-btn mt-3 mb-1 ml-3 text-lg">全体</div>
<div id="location-button" class="map-btn m-3 text-lg">現在地</div>
<!-- 投稿記入フォーム -->
<div class="mt-10 mb-40 px-3">
  <%= render 'shared/micropost_form' %>
</div>



<script>
function postMap() {
  // マップ表示
  const target = document.getElementById('post_map');
  const init_center = {lat: 38, lng: 138};
  const map = new google.maps.Map(target, {
    center: init_center,
    zoom: 5,
    zoomControl: false,
    mapTypeControl: false,
    streetViewControl: false,
    mapTypeControlOptions: {
      style: google.maps.MapTypeControlStyle.DROPDOWN_MENU
    },
    restriction: {
      latLngBounds: {
        north: 57.0,
        south: 18.0,
        west: 100.0,
        east: 180.0
      },
      strictBounds: false
    },
  });


  // マップクリック時のアクション設定
  let infoWindow;
  let marker = new google.maps.Marker();
  let geocoder = new google.maps.Geocoder();  
  map.addListener('click', function(e){
    geocoder.geocode({location: e.latLng}, function(results, status){
      if(status === 'OK' && results[0]) {

        let formatted_address = results[0].formatted_address;
        let address_components = results[0].address_components;

        let rets = results[0].address_components.filter(function(component) {
          return component.types.indexOf("administrative_area_level_1") > -1;
        });
        const location = results[0].geometry.location;

        // マーカーの生成
        if (marker){ marker.setMap(null) };
        marker = new google.maps.Marker({
          position: e.latLng,
          map: map,
          title: formatted_address,
          animation: google.maps.Animation.DROP
        });
        // 情報ウィンドウの生成
        infoWindow = new google.maps.InfoWindow({
          content: formatted_address
        });
        // マーカーにリスナーを設定
        marker.addListener('click', function(){
          infoWindow.open(map, marker);
          map.panTo(e.latLng);
        });
        // ピンをダブルクリック右クリックで拡大
        marker.addListener('rightclick', ()=> {
          map.panTo(e.latLng);
          map.setZoom(10);
        });
        marker.addListener('dblclick', ()=> {
          map.panTo(e.latLng);
          map.setZoom(10);
        });
        // 情報ウィンドウリスナーを設定
        infoWindow.addListener('closeclick', function(){
          marker.setMap(null);
        });
        // 隠しタグに座標を入力
        document.getElementById( "micropost_latlng" ).value = String(e.latLng);
        // クリック地点の都道府県をセレクトボックスに入力
        function change_pulldown(){
          pulldown_option = document.getElementById("micropost_prefecture_id").getElementsByTagName('option');
          for(i=0; i<pulldown_option.length; i++){
            if(pulldown_option[i].innerHTML == rets[0].long_name){
              pulldown_option[i].selected = true;
              break;
            }
          }
        }
        change_pulldown();

      }else if(status === 'ZERO_RESULTS') {
        alert('不明なアドレスです： ' + status);
        return;
      }else{
        alert('失敗しました： ' + status);
        return;
      }
    });
  });


  // 検索機能設定
  const input = document.getElementById("autocomplete");
  map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);
  const autocomplete = new google.maps.places.Autocomplete(
    input,
    {
      fields: ["geometry", "name"],
      componentRestrictions: {country: 'jp'}
    }
  );
  places = new google.maps.places.PlacesService(map);
  autocomplete.addListener("place_changed", onPlaceChanged);

  function onPlaceChanged() {
    const place = autocomplete.getPlace();

    if (place.geometry) {
      map.panTo(place.geometry.location);
      map.setZoom(15);
    } else {
      input.placeholder = "検索";
    }
  }


  // 全体ボタン設定
  // 宣言
  function initPosition(pushIntoMap, position) {
    const init_position = document.getElementById('init-position');
    pushIntoMap(position, init_position);
    google.maps.event.addDomListener(init_position, 'click', ()=> {
      map.panTo(init_center);
      map.setZoom(5);
    });
  }
  const pushIntoMap = function(position, init_position) {
    if (position === 'left') {
      map.controls[google.maps.ControlPosition.LEFT_BOTTOM].push(init_position);
    } else if (position === 'top') {
      map.controls[google.maps.ControlPosition.TOP].push(init_position);
    }
  }
  // 実行
  if (window.matchMedia('(max-width: 767px)').matches) {
    initPosition(pushIntoMap, 'left');
  } else if (window.matchMedia('(min-width:768px)').matches) {
    initPosition(pushIntoMap, 'top');
  }


  // 現在地ボタン設定
  const locationButton = document.getElementById('location-button');
  map.controls[google.maps.ControlPosition.RIGHT_BOTTOM].push(locationButton);
  new locationControl(locationButton, map);

  function locationControl(buttonDiv, map) {
    google.maps.event.addDomListener(buttonDiv, "click", function() {
      const infoWindow = new google.maps.InfoWindow; 
      
      // ブラウザが Geolocation に対応しているかを判定
      // 対応していない場合の処理
      if(!navigator.geolocation){ 
        infoWindow.setPosition(map.getCenter());
        infoWindow.setContent('Geolocation に対応していません。');
        infoWindow.open(map);
      }
      
      // ブラウザが対応している場合、position にユーザーの位置情報が入る
      navigator.geolocation.getCurrentPosition(
        
        // [第1引数] 取得に成功した場合の関数
        function(position) { 
        let pos = {  
          lat: position.coords.latitude,
          lng: position.coords.longitude,
        };
        infoWindow.setPosition(pos);
        infoWindow.setContent('現在位置を取得しました。');
        infoWindow.open(map);
        map.setCenter(pos);
        map.setZoom(12);
      }, 
      
      // [第2引数] 取得に失敗した場合の関数
      function(error) {

        let errorInfo = [
          "原因不明のエラーが発生しました。" ,
          "位置情報の取得が許可されませんでした。" ,
          "電波状況などで位置情報が取得できませんでした。" ,
          "位置情報の取得に時間がかかり過ぎてタイムアウトしました。"
        ];
        let errorNo = error.code ;
        let errorMessage = "[エラー番号: " + errorNo + "]\n" + errorInfo[ errorNo ] ;
        alert( errorMessage ) ;
      },

      // [第3引数] オプション
      {
        "enableHighAccuracy": false,
        "timeout": 4000,
        "maximumAge": 2000,
      });
    });
  }
}
</script> 
<script src="https://maps.googleapis.com/maps/api/js?language=ja&region=JP&key=AIzaSyCIX7ci0yBU4r9axzQEvNd5nefZiifw1bM&libraries=places&callback=postMap" async defer></script>