config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'map', to: 'pages#map'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  patch 'users/:id/edit', to: 'users#update'
  get 'login', to: 'sessions#new'
  get 'easylogin', to: 'sessions#easy'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'password_resets/new'
  get 'password_resets/edit'
  patch 'password_resets/:id/edit', to: 'password_resets#update'
  get 'password_resets', to: 'password_resets#new'
  get 'search', to: 'searches#search'
  get 'sort', to: 'searches#sort'
  resources :users, only: %i[show new create edit update destroy] do
    member do
      patch 'update_avatar'
      get 'following'
      get 'followers'
      get 'related_info'
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :microposts, only: %i[index new create destroy]
  resources :relationships, only: %i[create destroy]
  resources :goings, only: %i[create destroy]
end

app/views/layouts/_footer.html.erb
<footer class="fixed lg:hidden bottom-0 inset-x-0 h-12 border bg-white">
  <nav class="flex justify-around items-center h-12 pt-1 text-gray-500 text-center">
    <a href="/" class="footer_icon">
      <%= image_tag("home.svg", alt: "list", width: "30px", class: "mx-auto")%>
      <p class="h-5 text-sm leading-4">ホーム</p>
    </a>
    <a href="/map" class="footer_icon">
      <%= image_tag("map.svg", alt: "map", width: "30px", class: "mx-auto")%>
      <p class="h-5 text-sm leading-4">マップ</p>
    </a>
    <a href="/microposts" class="footer_icon">
      <%= image_tag("search.svg", alt: "serch", width: "30px", class: "mx-auto")%>
      <p class="h-5 text-sm leading-4">検索</p>
    </a>
  </nav>
</footer>
<div class="lg:hidden h-12"></div>

app/views/layouts/_header.html.erb
<header id="header" class="py-2 px-5 shadow-md">

  <div class="lg:max-w-6xl mx-auto flex justify-between">

    <div class="flex">
      <%= link_to image_tag("applogo.png", alt: "applogo", width: "42px", class: "rounded-lg"), root_path %>
      <%= link_to image_tag("appname.svg", alt: "appname", width: "80px", height: "42px", class: "hidden sm:block"), root_path, {class: "ml-2 flex"} %>
    </div>

    <% if logged_in? %>

    <nav>
      <ul class="flex justify-between list-none">
        <li class="mr-4">
          <a href="/microposts/new" class="btn-blue inline-block py-2 px-5">
              <%= image_tag("post.svg", alt: "post", width: "24px", class: "inline-block align-bottom") %>
              <p class="inline-block font-semibold">投稿する</p>
          </a>
        </li>

        <li class="">
        <%= link_to avatar_for(current_user), current_user %>
        </li>
      </ul>
    </nav>

    <% else %>

    <nav>
      <ul class="flex justify-between list-none w-56 text-xs">
        <li class="w-20 text-center text-green-600 hover:text-green-900 hover:underline">
          <%= link_to "簡単ログイン", easylogin_path, {class: "block leading-10"} %>
        </li>

        <li class="w-16 text-center text-green-600 hover:text-green-900 hover:underline">
          <%= link_to "ログイン", login_path, {class: "block leading-10"} %>
        </li>
        
        <li class="w-20">
          <%= link_to "新規登録", signup_path, {class: "btn-regreen block px-2 py-2 rounded-lg font-semibold text-center"} %>
        </li>
      </ul>
    </nav>

    <% end %>

  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<nav class="hidden lg:block sticky top-0 w-56">
  <div style="top: 30px" class="sticky border-r-2 mt-10 text-xl">

    <p class="w-10/12 mx-auto mb-16 border-b-2">
      <span class="block w-4/5 mx-auto">
        <%= link_to "ホーム", root_path, {class: "triangle"} %>
      </span>
    </p>
    <p class="w-10/12 mx-auto mb-16 border-b-2">
        <span class="block w-4/5 mx-auto">
        <%= link_to "マップ", map_path, {class: "triangle"} %>
        </span>
    </p>
    <p class="w-10/12 mx-auto mb-16 border-b-2">
        <span class="block w-4/5 mx-auto">
        <%= link_to "検索ページ", microposts_path, {class: "triangle"} %>
        </span>
    </p>
    <% if logged_in? %>
      <p class="w-10/12 mx-auto mb-16 border-b-2">
        <span class="block w-4/5 mx-auto">
          <%= link_to "ユーザー", current_user, {class: "triangle"} %>
        </span>
      </p>
    <% end %>

  <% if current_page?(map_path) %>
    <div class="w-10/12 mt-20 mx-auto py-6 px-5 rounded bg-gray-200 text-lg">
      <p>ピンを</br>ダブルクリックか</br>右クリックで拡大</p>
    </div>
  <% end %>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja" class="box-border">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= favicon_link_tag 'applogo.png'%>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
    <%= stylesheet_pack_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body class="overflow-y-auto text-gray-800">

    <%= render 'layouts/header' %>

    <div class="flex">

      <%= render 'layouts/sidebar' %>

      <div class="flex-grow w-64">
        <main class="">
          <% flash.each do |message_type, message| %>
            <div class="alert">
              <div class="alert-<%= message_type %>"><%= message %></div>
            </div>
          <% end %>
          <%= yield %>
        </main>
      </div>

    </div>

    <%#= debug(params) if Rails.env.development? %>

    <%= render 'layouts/footer' %>
  </body>
</html>